#kube config for tictactoe local run
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoegame
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe-container
        image: srinivasv147/tictactoe
---
apiVersion: v1
kind: Service
metadata:
  name: ttt-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: tictactoe
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001